### ISSUE TITLE
Purchase Appropriate Domains

### ISSUE THREAD

**Issue by enhinnen** [enhinnen/ResumeWeb#1]
- [ ] Requirements @enhinnen
- [ ] Config Task

----------

| **Details** |
|:--|
| 1) Purchase the domains listed below. |

| **`Domains`** |
| :-- |

| **URL** | **Price** | **Redirect or Main?**| **Purchased?** |
| :-- | :-- | :-- |  :-- |
| enhinnen.com | $3.00 for first year, $15 for 1 additional year | Redirect | <ul><li>- [ ] Purchased</li></ul> |
| ehinnen.com | $3.00 | Main | <ul><li>- [ ] Purchased</li></ul> |
| erinhinnen.com | $3.00 | Redirect | <ul><li>- [ ] Purchased</li></ul> |
| celloprojects.com | $3.00 for first year, $15 for 1 additional year | Main? | <ul><li>- [ ] Purchased</li></ul> |

**Comment by orabbani** [comment]
Domain purchased, DNS set up. https://celloprojects.com/wp-admin
