### ISSUE TITLE
Add SeedProd Coming Soon Page & Maintenance Mode Plugin

### ISSUE THREAD

**Issue by enhinnen** [enhinnen/ResumeWeb#5]
- [x] Requirements @enhinnen
- [ ] Dev Task @slinkyfromhell

----------

| **Details** |
|:--|
| 1) Install the SeedProd "Coming Soon Page & Maintenance Mode Plugin" on wordpress instance (see https://wordpress.org/plugins/coming-soon/ ) |
| 2) Create a maintenance mode page, design and content TBD |
| 3) Possibly create a coming soon page as well. |

**Comment by orabbani** [comment]
Installed SeedProd. Created 'Coming Soon' Page which is now visible when you go to the site. Let me know if you have an idea for background/font. My current options are somewhat limited. The default images can be found in WP Dashboard > Media. Standard dimensions are 2000x1333.
