### ISSUE TITLE
Link Gmail to Wordpress

### ISSUE THREAD

**Issue by enhinnen** [enhinnen/ResumeWeb#6]
- [ ] Requirements @slinkyfromhell
- [ ] Config Task @enhinnen

----------

| **Details** |
|:--|
| 1) Provide GMAIL credentials to wordpress so emails can be forwarded on my behalf. |

**Comment by orabbani** [comment]
Log in to WP. Dashboard > Settings > WP Mail SMTP Options. Set Mailer to Google. 
https://wpforms.com/how-to-securely-send-wordpress-emails-using-gmail-smtp/
Scroll down to Step 2:  Create a Web Application
I read through it; seems pretty simple. I'd set aside 30 minutes to read it and do everything.

**Comment by enhinnen** [comment]
@slinkyfromhell when I get to the step that says:

> Last, we need to fill out the Authorized redirect URIs field. To get the URI for your site, you’ll need to go back to the tab or window with your WordPress site. Still on the Settings » WP Mail SMTP page, you’ll need to look under the Gmail section for the field labeled Authorized redirect URI.<br><br>The value in this field should be your site’s URL followed by some extra details. You’ll need to copy this value, which is easily done by clicking the button with the copy icon.


However, when I follow these instructions and copy the authorized URI into gmail it says:

> Invalid Redirect: must end with a public top-level domain (such as .com or .org)


Therefore I believe we cannot enable this until we purchase a true top level domain?

Here's the how to article I was following: https://wpforms.com/how-to-securely-send-wordpress-emails-using-gmail-smtp/

**Comment by orabbani** [comment]
We have email through the celloprojects domain. I believe your current password is randomly generated. I can manually set one if you let me know what you want it to be
