### ISSUE TITLE
Set up SSL Cert via Let's Encrypt

### ISSUE THREAD

**Issue by enhinnen** [enhinnen/ResumeWeb#8]
- [ ] Requirements @enhinnen
- [x] Config Task @slinkyfromhell 

----------

| **Details** |
|:--|
| <ul><li>[ ] Prerequisite: Purchase domain</li></ul>|
| 1.) See https://mythemeshop.com/blog/lets-encrypt-free-ssl/ for setup. |

**Comment by orabbani** [comment]
Just as an update, I have a temporary self-signed SSL cert. I'm having trouble with let's encrypt so until I figure that out there's going to be warnings and issues with mobile in particular. To see how the site's coming along use a desktop browser.

**Comment by orabbani** [comment]
SSL is enabled on the site. If you go to http://www.celloprojects.com it should redirect to https
